const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { DatabaseSync } = require('node:sqlite')
const { createStore } = require('./store.cjs')

test('products and sales survive reopening; invalid sale leaves stock intact', () => {
  const folder = fs.mkdtempSync(path.join(os.tmpdir(), 'avaye-store-test-'))
  const file = path.join(folder, 'store.sqlite')
  let store = createStore(file)
  store.addProduct({ name: 'نان باگت', price: 30000, stock: 3 })
  const id = store.getState().products[0].id
  store.addSale({ productId: id, quantity: 2 })
  assert.throws(() => store.addSale({ productId: id, quantity: 2 }), /موجودی/)
  store.close()
  store = createStore(file)
  assert.equal(store.getState().products[0].stock, 1)
  assert.equal(store.getState().sales[0].total, 60000)
  assert.equal(store.getState().sales.length, 1)
  store.close()
})

test('backup restores a verified snapshot', async () => {
  const folder = fs.mkdtempSync(path.join(os.tmpdir(), 'avaye-backup-test-'))
  const store = createStore(path.join(folder, 'store.sqlite'))
  store.addExpense({ name: 'آرد', amount: 100000 })
  const backupFile = path.join(folder, 'backup.sqlite')
  await store.backupTo(backupFile)
  store.addExpense({ name: 'برق', amount: 50000 })
  const restored = await store.restoreFrom(backupFile)
  assert.equal(restored.expenses.length, 1)
  assert.equal(restored.expenses[0].name, 'آرد')
  assert.ok(fs.readdirSync(folder).some((name) => name.startsWith('before-restore-')))
  store.close()
})

test('user can maintain a product list and stock changes are recorded', () => {
  const folder = fs.mkdtempSync(path.join(os.tmpdir(), 'avaye-products-test-'))
  const store = createStore(path.join(folder, 'store.sqlite'))
  assert.equal(store.getState().products.length, 0)
  store.addProduct({ name: 'نان تست', category: 'نان', sku: 'B-01', barcode: '123456', unit: 'بسته', price: 75000, purchasePrice: 50000, stock: 4, minStock: 2 })
  const item = store.getState().products[0]
  store.updateProduct({ ...item, name: 'نان تست بزرگ', price: 85000, active: false })
  assert.throws(() => store.addSale({ productId: item.id, quantity: 1 }), /غیرفعال/)
  store.adjustStock({ productId: item.id, change: -2, reason: 'انبارگردانی' })
  assert.equal(store.getState().products[0].stock, 2)
  assert.equal(store.getState().products[0].name, 'نان تست بزرگ')
  assert.throws(() => store.adjustStock({ productId: item.id, change: -3, reason: 'خطا' }), /موجودی/)
  store.close()
})

test('version 1 database migrates without losing products', () => {
  const folder = fs.mkdtempSync(path.join(os.tmpdir(), 'avaye-migrate-test-'))
  const file = path.join(folder, 'store.sqlite')
  const old = new DatabaseSync(file)
  old.exec("CREATE TABLE products (id INTEGER PRIMARY KEY, name TEXT NOT NULL, price INTEGER NOT NULL, stock INTEGER NOT NULL); INSERT INTO products (name, price, stock) VALUES ('نان باگت', 30000, 5); PRAGMA user_version = 1")
  old.close()
  const store = createStore(file)
  assert.equal(store.getState().products[0].name, 'نان باگت')
  assert.equal(store.getState().products[0].unit, 'عدد')
  store.close()
})
